# Exemplo 01 Makefile
#
# Help about Makefiles:
# http://mrbook.org/blog/tutorials/make/
#
# Syntax:
#	target: dependencies
#	[tab] system command

CC = g++
FLAGS = -O2
SOURCES = src/libs/*.cpp src/*.cpp
EXECUTABLE = bin/exemplo01

all:
	$(CC) $(FLAGS) -o $(EXECUTABLE) $(SOURCES)